# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a7c1aba773905a854ae83f84be58ec05c52c9ab7a52f44e8c30c7924f600729c3e16074e8f06372757405254aeb2e03641ce811d34ae035b05358eadba41c16

test:
  secret_key_base: 0b4a1df1b7d8841318424c8b9f46882e1a0a1adc77b1b522904307c6b716756e2be1b56353b5d7b60b8cf8f192f694ce0a41a3b80263dd2581d49b06eeaa02a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
